quarkus.http.port=8081

quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=1000

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:8080

%test.quarkus.http.test-port=0

%test.quarkus.keycloak.devservices.enabled=false
%test.quarkus.oidc.tenant-enabled=false
